POST http://localhost:3001/admission/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imdvb2dsZTExMzYwMzE5MjAyNDk4MTU4MTA3MSIsImVtYWlsIjoibmlraGl0YS5wdW5hdGlAaGFja2lsbGlub2lzLm9yZyIsInByb3ZpZGVyIjoiZ29vZ2xlIiwicm9sZXMiOlsiU1RBRkYiXSwiZXhwIjoxNjk3NzM4OTA1LjIyMSwiaWF0IjoxNjk3NjUyNTA1fQ.TiyjUzyRBSRgiJ5YeEHrt-9sQaoCjkgcmMoVgqXq0-U
Content-Type: application/json

{
  "userId": "user5",
  "status": "WAITLISTED",
  "response": "PENDING",
  "reviewer": "reviewer1",
  "emailSent": true
}

###
GET http://localhost:3001/admission/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imdvb2dsZTExMzYwMzE5MjAyNDk4MTU4MTA3MSIsImVtYWlsIjoibmlraGl0YS5wdW5hdGlAaGFja2lsbGlub2lzLm9yZyIsInByb3ZpZGVyIjoiZ29vZ2xlIiwicm9sZXMiOlsiU1RBRkYiXSwiZXhwIjoxNjk3NzM4OTA1LjIyMSwiaWF0IjoxNjk3NjUyNTA1fQ.TiyjUzyRBSRgiJ5YeEHrt-9sQaoCjkgcmMoVgqXq0-U

###
PUT http://localhost:3001/admission/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imdvb2dsZTExMzYwMzE5MjAyNDk4MTU4MTA3MSIsImVtYWlsIjoibmlraGl0YS5wdW5hdGlAaGFja2lsbGlub2lzLm9yZyIsInByb3ZpZGVyIjoiZ29vZ2xlIiwicm9sZXMiOlsiU1RBRkYiXSwiZXhwIjoxNjk3NzM4OTA1LjIyMSwiaWF0IjoxNjk3NjUyNTA1fQ.TiyjUzyRBSRgiJ5YeEHrt-9sQaoCjkgcmMoVgqXq0-U
Content-Type: application/json

{
  "entries": [
    {
    "userId": "user1",
    "name": "Jason",
    "status": "ACCEPTED"
    },
    {
      "userId": "user2",
      "name": "Fred",
      "status": "REJECTED"
    },
    {
      "userId": "user3",
      "name": "John",
      "status": "REJECTED"
    }
  ]
}