name: Generate Dev Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Generate dev docs
      run: npm run docs
    - name: Push dev docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: HackIllinois/adonix-dev-docs
        publish_branch: main
        publish_dir: ./devdocs/
