name: Generate API Documentation
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Generate docs
      run: npm run apidocs
    - name: Push API docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: HackIllinois/adonix-api-docs
        publish_branch: main
        publish_dir: ./apidocs/
