name: Update Prod-Hotfix

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-prod-hotfix:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Synchronize prod-hotfix with main
        run: |
          git checkout --track origin/prod-hotfix
          git reset --hard main
          git push --force origin prod-hotfix
