name: Create and Auto-Merge PR to prod-hotfix

on:
  push:
    branches:
      - main

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create PR
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          # Create a new branch for changes
          git checkout -b prod-hotfix

          # Make desired changes to the code
          git reset --hard main

          # Push the branch to the remote repository
          git push origin prod-hotfix

          # Create a pull request using GitHub API
          curl -X POST \
            -H "Authorization: token $ACTIONS_PAT" \
            -d '{
              "title": "Feature: Update Prod Hotfix",
              "body": "This PR brings prod-hotfix back up to match main.",
              "head": "prod-hotfix",
              "base": "main"
            }' \
            "https://api.github.com/repos/HackIllinois/Adonix/pulls"

      - name: Auto-merge PR
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          # Merge the PR using GitHub API
          PR_NUMBER=$(curl -s -H "Authorization: token $ACTIONS_PAT" \
            "https://api.github.com/repos/HackIllinois/Adonix/pulls?head=HackIllinois:feature-branch" \
            | jq -r '.[0].number')

          curl -X PUT \
            -H "Authorization: token $ACTIONS_PAT" \
            -d '{"merge_method":"rebase"}' \
            "https://api.github.com/repos/HackIllinois/Adonix/pulls/$PR_NUMBER/merge"
